FROM apache/airflow:2.8.1

USER root
RUN apt-get update && apt-get install -y git && rm -rf /var/lib/apt/lists/*

USER airflow
RUN pip install --no-cache-dir \
    pandas \
    numpy \
    scikit-learn==1.3.2 \
    xgboost==2.0.3 \
    imbalanced-learn \
    ucimlrepo \
    pyyaml \
    matplotlib \
    dvc \
    mlflow